# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests
on: [push, pull_request]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, '3.10']
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: ${{matrix.python}}
        architecture: x64

    - name: install Python packages
      run: |
        pip install archspec==0.2.2

    - name: test eessi_software_subdir.py script
      run: |
          ./eessi_software_subdir.py | tee out
          grep '^x86_64/' out
          egrep '/intel/|/amd/' out
