# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test software licenses
on:
  push:
    branches: [ "*-software.eessi.io" ]
  pull_request:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

        - name: set up Python
          uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
          with:
            python-version: '3.9'

        - name: Check software licenses
          run: |
            python licenses/spdx.py licenses/licenses.json
